version: "3.1"

services:
#  tomcat:
#    container_name: tomcat
#    build: ../../arc-expenses-service
#    ports:
#      - "8009:8009"
#      - "8380:8080"
#    links:
##      - db
##      - elastic
##      - jms
##      - apache_shibboleth_sp
#      - arc_proxy_shibboleth
#    networks:
#      - arcnet
#    secrets:
#      - source: db_file
#    restart: unless-stopped

  platform:
    container_name: platform
    build: ../../../arc-expenses-ui
    ports:
      - "3000:80"
    networks:
      - arcnet
    restart: unless-stopped



  arc_proxy_shibboleth:
      container_name: arc_proxy_shibboleth
      build:
        context: arc_proxy_shibboleth
      secrets:
        - source: sp_key
      ports:
        - "443:443"
        - "80:80"
      networks:
        - arcnet
      restart: unless-stopped


#  idp:
#      build: idp
#      container_name: idp
#      environment:
#       - JETTY_MAX_HEAP=64m
#       - JETTY_BROWSER_SSL_KEYSTORE_PASSWORD=password
#       - JETTY_BACKCHANNEL_SSL_KEYSTORE_PASSWORD=password
#      expose:
#       - "8443"
#      ports:
#       - "4443:4443"
#      networks:
#       - arcnet
#      secrets:
#       - source: idp_backchannel
#       - source: idp_browser
#       - source: idp_encryption
#       - source: idp_signing
#       - source: idp_sealer

#  ldap:
#    image: osixia/openldap:1.2.1
#    container_name: ldap
#    environment:
#      LDAP_LOG_LEVEL: "256"
#      LDAP_ORGANISATION: "Example Inc."
#      LDAP_DOMAIN: "example.org"
#      LDAP_BASE_DN: ""
#      LDAP_ADMIN_PASSWORD: "admin"
#      LDAP_CONFIG_PASSWORD: "config"
#      LDAP_READONLY_USER: "false"
#      #LDAP_READONLY_USER_USERNAME: "readonly"
#      #LDAP_READONLY_USER_PASSWORD: "readonly"
#      LDAP_RFC2307BIS_SCHEMA: "false"
#      LDAP_BACKEND: "mdb"
#      LDAP_TLS: "true"
#      LDAP_TLS_CRT_FILENAME: "ldap.crt"
#      LDAP_TLS_KEY_FILENAME: "ldap.key"
#      LDAP_TLS_CA_CRT_FILENAME: "ca.crt"
#      LDAP_TLS_ENFORCE: "false"
#      LDAP_TLS_CIPHER_SUITE: "SECURE256:-VERS-SSL3.0"
#      LDAP_TLS_PROTOCOL_MIN: "3.1"
#      LDAP_TLS_VERIFY_CLIENT: "demand"
#      LDAP_REPLICATION: "false"
#      #LDAP_REPLICATION_CONFIG_SYNCPROV: "binddn="cn=admin,cn=config" bindmethod=simple credentials=$LDAP_CONFIG_PASSWORD searchbase="cn=config" type=refreshAndPersist retry="60 +" timeout=1 starttls=critical"
#      #LDAP_REPLICATION_DB_SYNCPROV: "binddn="cn=admin,$LDAP_BASE_DN" bindmethod=simple credentials=$LDAP_ADMIN_PASSWORD searchbase="$LDAP_BASE_DN" type=refreshAndPersist interval=00:00:00:10 retry="60 +" timeout=1 starttls=critical"
#      #LDAP_REPLICATION_HOSTS: "#PYTHON2BASH:['ldap://ldap.example.org','ldap://ldap2.example.org']"
#      KEEP_EXISTING_CONFIG: "false"
#      LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"
#      LDAP_SSL_HELPER_PREFIX: "ldap"
#    tty: true
#    stdin_open: true
#    volumes:
#      - /var/lib/ldap
#      - /etc/ldap/slapd.d
#      - /container/service/slapd/assets/certs/
#    ports:
#      - "389:389"
#      - "636:636"
#    domainname: "example.org" # important: same as hostname
#    hostname: "example.org"
#
#  phpldapadmin:
#    image: osixia/phpldapadmin:latest
#    container_name: phpldapadmin
#    environment:
#      PHPLDAPADMIN_LDAP_HOSTS: "ldap"
#      PHPLDAPADMIN_HTTPS: "false"
#    ports:
#      - "8080:80"
#    depends_on:
#      - ldap

#  db:
#    container_name: postgres
#    build: registry-postgres
#    ports:
#      - "5432:5432"
#    volumes:
#      - pgdata:/var/lib/postgresql/data
#    networks:
#      - arcnet
#    restart: unless-stopped
  jms:
    container_name: jms
    image: rmohr/activemq:5.14.0-alpine
    ports:
      - "61616:61616"
    networks:
      - arcnet
    restart: unless-stopped
#  elastic:
#    container_name: elastic
#    image: docker.elastic.co/elasticsearch/elasticsearch:5.2.2
#    #image: elasticsearch:5.2.2-alpine
#    environment:
#      - cluster.name=docker-cluster
#      - bootstrap.memory_lock=true
#      - xpack.security.enabled=false
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#      nofile:
#        soft: 65536
#        hard: 65536
#    mem_limit: 1g
#    cap_add:
#      - IPC_LOCK
##    volumes:
##      - esdata1:/usr/share/elasticsearch/data
#    ports:
#      - "9222:9200"
#      - "9333:9300"
#
#    networks:
#      - esnet
#    restart: unless-stopped
#  elasticsearch2:
#    image: docker.elastic.co/elasticsearch/elasticsearch:5.2.2
#    #image: elasticsearch:5.2.2-alpine
#    container_name: elasticsearch2
#    environment:
#      - cluster.name=docker-cluster
#      - bootstrap.memory_lock=true
#      - xpack.security.enabled=false
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#      - "discovery.zen.ping.unicast.hosts=elastic"
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#      nofile:
#        soft: 65536
#        hard: 65536
#    mem_limit: 1g
#    cap_add:
#      - IPC_LOCK
##    volumes:
##      - esdata2:/usr/share/elasticsearch/data
#    networks:
#      - esnet
#    restart: unless-stopped
volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local
  pgdata:
    driver: local

networks:
  arcnet:
    driver: bridge

secrets:
  idp_backchannel:
    file: ./secret/idp-backchannel.p12
  idp_browser:
    file: ./secret/idp-browser.p12
  idp_encryption:
    file: ./secret/idp-encryption.key
  idp_signing:
    file: ./secret/idp-signing.key
  idp_sealer:
    file: ./secret/sealer.jks
  sp_key:
    file: ./secret/sp-key.pem
  db_file:
    file: ./secret/secret.env
  ssp_key:
    file: ./secret/server.pem